package context_test

import (
	"encoding/json"
	"fmt"
	"strings"
	"testing"

	. "github.com/onsi/gomega"

	sessionctx "github.com/toejough/engram/internal/context"
)

// TestStrip_DropsLocalCommandStdout verifies that USER turns containing only
// <local-command-stdout> or the local-command-caveat are dropped.
func TestStrip_DropsLocalCommandStdout(t *testing.T) {
	t.Parallel()

	stdoutContent := "<local-command-stdout>Catch you later!</local-command-stdout>"
	caveatContent := "<local-command-caveat>Caveat: The messages below were generated by the user " +
		"while running local commands. DO NOT respond to these messages or otherwise consider them " +
		"in your response unless the user explicitly asks you to.</local-command-caveat>"

	stdoutLine := jsonlUserLine(stdoutContent)
	caveaLine := jsonlUserLine(caveatContent)

	t.Run("stdout_Strip", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.Strip([]string{stdoutLine})

		g.Expect(result).To(BeEmpty())
	})

	t.Run("stdout_ToolSummaryMode", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.StripWithConfig([]string{stdoutLine}, sessionctx.StripConfig{ToolSummaryMode: true})

		g.Expect(result).To(BeEmpty())
	})

	t.Run("caveat_Strip", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.Strip([]string{caveaLine})

		g.Expect(result).To(BeEmpty())
	})

	t.Run("caveat_ToolSummaryMode", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.StripWithConfig([]string{caveaLine}, sessionctx.StripConfig{ToolSummaryMode: true})

		g.Expect(result).To(BeEmpty())
	})
}

// --- Harness injection filtering ---

// TestStrip_DropsSkillBodyInjection verifies that USER turns injected by the
// skill harness (starting with "Base directory for this skill:") are dropped.
// Both Strip and ToolSummaryMode paths must filter them.
func TestStrip_DropsSkillBodyInjection(t *testing.T) {
	t.Parallel()

	skillBody := "Base directory for this skill: /Users/joe/.claude/skills/recall\n\n" +
		"# Recall\nThis is the entire SKILL.md content that should be dropped entirely."

	skillLine := jsonlUserBlockLine(skillBody)

	assistantLine := `{"type":"assistant","message":{"role":"assistant",` +
		`"content":[{"type":"text","text":"Searching the vault."}]}}`

	lines := []string{skillLine, assistantLine}

	t.Run("Strip", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.Strip(lines)

		g.Expect(result).To(HaveLen(1))
		g.Expect(result[0]).To(Equal("ASSISTANT: Searching the vault."))
	})

	t.Run("ToolSummaryMode", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.StripWithConfig(lines, sessionctx.StripConfig{ToolSummaryMode: true})

		g.Expect(result).To(HaveLen(1))
		g.Expect(result[0]).To(Equal("ASSISTANT: Searching the vault."))
	})
}

// TestStrip_DropsSlashCommandWithNoArgs verifies that a slash-command USER turn
// with no <command-args> block is dropped entirely.
func TestStrip_DropsSlashCommandWithNoArgs(t *testing.T) {
	t.Parallel()

	cmdContent := "<command-message>learn</command-message>\n<command-name>/learn</command-name>"

	cmdLine := jsonlUserLine(cmdContent)

	lines := []string{cmdLine}

	t.Run("Strip", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.Strip(lines)

		g.Expect(result).To(BeEmpty())
	})

	t.Run("ToolSummaryMode", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.StripWithConfig(lines, sessionctx.StripConfig{ToolSummaryMode: true})

		g.Expect(result).To(BeEmpty())
	})
}

func TestStrip_DropsSystemReminderContent(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	sysReminderOnly := `{"type":"user","message":{"role":"user",` +
		`"content":[{"type":"text",` +
		`"text":"<system-reminder>engram hook output</system-reminder>"}]}}`
	mixedContent := `{"type":"user","message":{"role":"user",` +
		`"content":[{"type":"text",` +
		`"text":"<system-reminder>hook noise</system-reminder>"},` +
		`{"type":"text","text":"yes, do that"}]}}`
	assistantLine := `{"type":"assistant","message":{"role":"assistant",` +
		`"content":[{"type":"text","text":"OK, doing it."}]}}`

	lines := []string{
		sysReminderOnly,
		mixedContent,
		assistantLine,
	}

	result := sessionctx.Strip(lines)

	g.Expect(result).To(HaveLen(2))
	g.Expect(result[0]).To(Equal("USER: yes, do that"))
	g.Expect(result[1]).To(Equal("ASSISTANT: OK, doing it."))
}

// TestStrip_ExtractsCommandArgsFromSlashCommand verifies that slash-command
// USER turns are reduced to just the <command-args> inner text (the real ask),
// dropping all boilerplate tags.
func TestStrip_ExtractsCommandArgsFromSlashCommand(t *testing.T) {
	t.Parallel()

	// Slash-command format: <command-message>, <command-name>, <command-args>
	cmdContent := "<command-message>learn</command-message>\n" +
		"<command-name>/learn</command-name>\n" +
		"<command-args>that I always use targ, not go test directly</command-args>"

	cmdLine := jsonlUserLine(cmdContent)

	assistantLine := `{"type":"assistant","message":{"role":"assistant",` +
		`"content":[{"type":"text","text":"Noted."}]}}`

	lines := []string{cmdLine, assistantLine}

	t.Run("Strip", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.Strip(lines)

		g.Expect(result).To(HaveLen(2))
		g.Expect(result[0]).To(Equal("USER: that I always use targ, not go test directly"))
		g.Expect(result[1]).To(Equal("ASSISTANT: Noted."))
	})

	t.Run("ToolSummaryMode", func(t *testing.T) {
		t.Parallel()

		g := NewGomegaWithT(t)
		result := sessionctx.StripWithConfig(lines, sessionctx.StripConfig{ToolSummaryMode: true})

		g.Expect(result).To(HaveLen(2))
		g.Expect(result[0]).To(Equal("USER: that I always use targ, not go test directly"))
		g.Expect(result[1]).To(Equal("ASSISTANT: Noted."))
	})
}

// --- Strip extracts text content from JSON, drops tool noise ---

func TestStrip_ExtractsTextFromUserMessages(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	toolResultLine := `{"type":"user","message":{"role":"user",` +
		`"content":[{"type":"tool_result","tool_use_id":"toolu_123",` +
		`"content":"package recall\nimport fmt"}]}}`
	assistantWithTool := `{"type":"assistant","message":{"role":"assistant",` +
		`"content":[{"type":"text","text":"Let me check the code."},` +
		`{"type":"tool_use","id":"toolu_123","name":"Read",` +
		`"input":{"path":"/foo.go"}}]}}`

	lines := []string{
		`{"type":"user","message":{"role":"user","content":"what was I working on?"}}`,
		toolResultLine,
		assistantWithTool,
		`{"type":"assistant","message":{"role":"assistant",` +
			`"content":[{"type":"text","text":"The bug is fixed."}]}}`,
		`{"type":"progress","data":{"type":"hook_progress"}}`,
	}

	result := sessionctx.Strip(lines)

	g.Expect(result).To(HaveLen(3))
	g.Expect(result[0]).To(Equal("USER: what was I working on?"))
	g.Expect(result[1]).To(Equal("ASSISTANT: Let me check the code."))
	g.Expect(result[2]).To(Equal("ASSISTANT: The bug is fixed."))
}

// --- Strip filters by JSONL type field ---

func TestStrip_FiltersProgressAndSystemEntries(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	lines := []string{
		`{"type":"progress","data":{"type":"hook_progress"}}`,
		`{"type":"user","message":{"role":"user","content":"hello"}}`,
		`{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"hi"}]}}`,
		`{"type":"system","data":"init"}`,
		`{"type":"file-history-snapshot","data":{}}`,
		`{"type":"last-prompt","data":{}}`,
		`{"type":"user","message":{"role":"user","content":"bye"}}`,
	}

	result := sessionctx.Strip(lines)

	g.Expect(result).To(HaveLen(3))
	g.Expect(result[0]).To(Equal("USER: hello"))
	g.Expect(result[1]).To(Equal("ASSISTANT: hi"))
	g.Expect(result[2]).To(Equal("USER: bye"))
}

func TestStrip_HandlesStringContentInUserMessages(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	lines := []string{
		`{"type":"user","message":{"role":"user","content":"plain string message"}}`,
		`{"type":"user","message":{"role":"user","content":"<system-reminder>noise</system-reminder>"}}`,
	}

	result := sessionctx.Strip(lines)

	g.Expect(result).To(HaveLen(1))
	g.Expect(result[0]).To(Equal("USER: plain string message"))
}

func TestStrip_LegacyRoleFallback(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	// Legacy format: role at message level, no outer type field.
	lines := []string{
		`{"message":{"role":"user","content":"legacy user msg"}}`,
		`{"message":{"role":"assistant","content":"legacy assistant msg"}}`,
		`{"message":{"role":"toolUse","content":"should be dropped"}}`,
	}

	result := sessionctx.Strip(lines)

	g.Expect(result).To(HaveLen(2))
	g.Expect(result[0]).To(Equal("USER: legacy user msg"))
	g.Expect(result[1]).To(Equal("ASSISTANT: legacy assistant msg"))
}

// --- T-138: ContentStripper removes tool result blocks ---

func TestT138_StripRemovesToolResultBlocks(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	lines := []string{
		`{"type":"user","message":{"role":"user","content":"hello"}}`,
		`{"role":"toolResult","content":"big result data"}`,
		`{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"response"}]}}`,
	}

	result := sessionctx.Strip(lines)

	g.Expect(result).To(HaveLen(2))
	g.Expect(result[0]).To(Equal("USER: hello"))
	g.Expect(result[1]).To(Equal("ASSISTANT: response"))
}

// --- T-139: ContentStripper replaces base64 strings ---

func TestT139_StripReplacesBase64Strings(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	// Generate a base64-like string >100 chars.
	longBase64 := strings.Repeat("QUFB", 30) // 120 chars of valid base64

	line := fmt.Sprintf(
		`{"type":"user","message":{"role":"user","content":"data:image/png;base64,%s"}}`,
		longBase64,
	)

	result := sessionctx.Strip([]string{line})

	g.Expect(result).To(HaveLen(1))
	g.Expect(result[0]).To(ContainSubstring("[base64 removed]"))
	g.Expect(result[0]).NotTo(ContainSubstring(longBase64))
	g.Expect(result[0]).To(HavePrefix("USER: "))
}

// --- T-140: ContentStripper truncates oversized content blocks ---

func TestT140_StripTruncatesOversizedContent(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	const maxContentLen = 2000

	oversized := strings.Repeat("hello world ", maxContentLen/12+50)
	line := fmt.Sprintf(`{"type":"user","message":{"role":"user","content":"%s"}}`, oversized)

	result := sessionctx.Strip([]string{line})

	g.Expect(result).To(HaveLen(1))
	g.Expect(result[0]).To(HavePrefix("USER: "))
	g.Expect(result[0]).To(ContainSubstring("[truncated]"))
	g.Expect(len(result[0])).To(BeNumerically("<=", maxContentLen+len("[truncated]")))
}

// --- T-141: ContentStripper preserves user messages ---

func TestT141_StripPreservesUserMessages(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	line := `{"type":"user","message":{"role":"user","content":"please help me"}}`

	result := sessionctx.Strip([]string{line})

	g.Expect(result).To(HaveLen(1))
	g.Expect(result[0]).To(Equal("USER: please help me"))
}

// --- T-142: ContentStripper preserves assistant text ---

func TestT142_StripPreservesAssistantText(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	line := `{"type":"assistant","message":{"role":"assistant","content":"here is my answer"}}`

	result := sessionctx.Strip([]string{line})

	g.Expect(result).To(HaveLen(1))
	g.Expect(result[0]).To(Equal("ASSISTANT: here is my answer"))
}

// --- T-143: ContentStripper preserves tool names, removes tool results ---

func TestT143_StripDropsToolUseAndToolResultLines(t *testing.T) {
	t.Parallel()

	g := NewGomegaWithT(t)

	lines := []string{
		`{"role":"toolUse","name":"Bash","command":"ls -la","content":"tool use details"}`,
		`{"role":"toolResult","content":"drwxr-xr-x 5 user staff 160 Mar  7 file1\nfile2\nfile3"}`,
	}

	result := sessionctx.Strip(lines)

	g.Expect(result).To(BeEmpty())
}

// jsonlUserBlockLine builds a JSONL user line with a single text block in an array.
func jsonlUserBlockLine(text string) string {
	type block struct {
		Type string `json:"type"`
		Text string `json:"text"`
	}

	blocks := []block{{Type: "text", Text: text}}

	blocksJSON, err := json.Marshal(blocks)
	if err != nil {
		panic(err)
	}

	return `{"type":"user","message":{"role":"user","content":` + string(blocksJSON) + `}}`
}

// jsonlUserLine builds a JSONL user line with a plain string content field.
func jsonlUserLine(content string) string {
	marshaled, err := json.Marshal(content)
	if err != nil {
		panic(err)
	}

	return `{"type":"user","message":{"role":"user","content":` + string(marshaled) + `}}`
}
