// Code generated by impgen. DO NOT EDIT.
// impgen:hash:0db2d6a75cbda866

package memory

import (
	_imptest "github.com/toejough/imptest"
)

type EmbedderImp struct {
	Embed *EmbedderMockEmbedMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *EmbedderImpEventually
}

type EmbedderImpEventually struct {
	Embed *EmbedderMockEmbedMethod
}

type EmbedderMockEmbedArgs struct {
	Text string
}

type EmbedderMockEmbedCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *EmbedderMockEmbedCall) GetArgs() EmbedderMockEmbedArgs {
	raw := c.RawArgs()
	return EmbedderMockEmbedArgs{
		Text: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *EmbedderMockEmbedCall) Return(result0 []float32, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type EmbedderMockEmbedMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *EmbedderMockEmbedMethod) ArgsEqual(text string) *EmbedderMockEmbedCall {
	call := m.DependencyMethod.ArgsEqual(text)
	return &EmbedderMockEmbedCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *EmbedderMockEmbedMethod) ArgsShould(matchers ...any) *EmbedderMockEmbedCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &EmbedderMockEmbedCall{DependencyCall: call}
}

// MockEmbedder creates a mock Embedder and returns (mock, expectation handle).
func MockEmbedder(t _imptest.TestReporter) (Embedder, *EmbedderImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &EmbedderImp{
		Embed: newEmbedderMockEmbedMethod(_imptest.NewDependencyMethod(ctrl, "Embed")),
	}
	imp.Eventually = &EmbedderImpEventually{
		Embed: newEmbedderMockEmbedMethod(_imptest.NewDependencyMethod(ctrl, "Embed").AsEventually()),
	}
	mock := &mockEmbedderImpl{ctrl: ctrl}
	return mock, imp
}

type mockEmbedderImpl struct {
	ctrl *_imptest.Imp
}

// Embed implements Embedder.Embed.
func (impl *mockEmbedderImpl) Embed(text string) ([]float32, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Embed",
		Args:         []any{text},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []float32
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]float32); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newEmbedderMockEmbedMethod creates a typed method wrapper.
func newEmbedderMockEmbedMethod(dm *_imptest.DependencyMethod) *EmbedderMockEmbedMethod {
	return &EmbedderMockEmbedMethod{DependencyMethod: dm}
}
