// Code generated by impgen. DO NOT EDIT.
// impgen:hash:556cb28eb66fe1bc

package transcript_test

import (
	transcript "github.com/toejough/engram/internal/transcript"
	_imptest "github.com/toejough/imptest"
	time "time"
)

type ReaderImp struct {
	ReadFrom *ReaderMockReadFromMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *ReaderImpEventually
}

type ReaderImpEventually struct {
	ReadFrom *ReaderMockReadFromMethod
}

type ReaderMockReadFromArgs struct {
	Path        string
	FromTime    time.Time
	BudgetBytes int
}

type ReaderMockReadFromCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ReaderMockReadFromCall) GetArgs() ReaderMockReadFromArgs {
	raw := c.RawArgs()
	return ReaderMockReadFromArgs{
		Path:        raw[0].(string),
		FromTime:    raw[1].(time.Time),
		BudgetBytes: raw[2].(int),
	}
}

// Return specifies the typed values the mock should return.
func (c *ReaderMockReadFromCall) Return(result0 transcript.ReadResult, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type ReaderMockReadFromMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *ReaderMockReadFromMethod) ArgsEqual(path string, fromTime time.Time, budgetBytes int) *ReaderMockReadFromCall {
	call := m.DependencyMethod.ArgsEqual(path, fromTime, budgetBytes)
	return &ReaderMockReadFromCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *ReaderMockReadFromMethod) ArgsShould(matchers ...any) *ReaderMockReadFromCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &ReaderMockReadFromCall{DependencyCall: call}
}

// MockReader creates a mock Reader and returns (mock, expectation handle).
func MockReader(t _imptest.TestReporter) (transcript.Reader, *ReaderImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &ReaderImp{
		ReadFrom: newReaderMockReadFromMethod(_imptest.NewDependencyMethod(ctrl, "ReadFrom")),
	}
	imp.Eventually = &ReaderImpEventually{
		ReadFrom: newReaderMockReadFromMethod(_imptest.NewDependencyMethod(ctrl, "ReadFrom").AsEventually()),
	}
	mock := &mockReaderImpl{ctrl: ctrl}
	return mock, imp
}

type mockReaderImpl struct {
	ctrl *_imptest.Imp
}

// ReadFrom implements transcript.Reader.ReadFrom.
func (impl *mockReaderImpl) ReadFrom(path string, fromTime time.Time, budgetBytes int) (transcript.ReadResult, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReadFrom",
		Args:         []any{path, fromTime, budgetBytes},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 transcript.ReadResult
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(transcript.ReadResult); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newReaderMockReadFromMethod creates a typed method wrapper.
func newReaderMockReadFromMethod(dm *_imptest.DependencyMethod) *ReaderMockReadFromMethod {
	return &ReaderMockReadFromMethod{DependencyMethod: dm}
}
