// Code generated by impgen. DO NOT EDIT.
// impgen:hash:6c4da39844f2c2b6

package transcript_test

import (
	transcript "github.com/toejough/engram/internal/transcript"
	_imptest "github.com/toejough/imptest"
)

type ReaderImp struct {
	Read *ReaderMockReadMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *ReaderImpEventually
}

type ReaderImpEventually struct {
	Read *ReaderMockReadMethod
}

type ReaderMockReadArgs struct {
	Path        string
	BudgetBytes int
}

type ReaderMockReadCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ReaderMockReadCall) GetArgs() ReaderMockReadArgs {
	raw := c.RawArgs()
	return ReaderMockReadArgs{
		Path:        raw[0].(string),
		BudgetBytes: raw[1].(int),
	}
}

// Return specifies the typed values the mock should return.
func (c *ReaderMockReadCall) Return(result0 string, result1 int, result2 error) {
	c.DependencyCall.Return(result0, result1, result2)
}

type ReaderMockReadMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *ReaderMockReadMethod) ArgsEqual(path string, budgetBytes int) *ReaderMockReadCall {
	call := m.DependencyMethod.ArgsEqual(path, budgetBytes)
	return &ReaderMockReadCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *ReaderMockReadMethod) ArgsShould(matchers ...any) *ReaderMockReadCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &ReaderMockReadCall{DependencyCall: call}
}

// MockReader creates a mock Reader and returns (mock, expectation handle).
func MockReader(t _imptest.TestReporter) (transcript.Reader, *ReaderImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &ReaderImp{
		Read: newReaderMockReadMethod(_imptest.NewDependencyMethod(ctrl, "Read")),
	}
	imp.Eventually = &ReaderImpEventually{
		Read: newReaderMockReadMethod(_imptest.NewDependencyMethod(ctrl, "Read").AsEventually()),
	}
	mock := &mockReaderImpl{ctrl: ctrl}
	return mock, imp
}

type mockReaderImpl struct {
	ctrl *_imptest.Imp
}

// Read implements transcript.Reader.Read.
func (impl *mockReaderImpl) Read(path string, budgetBytes int) (string, int, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Read",
		Args:         []any{path, budgetBytes},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	var result2 int
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(int); ok {
			result2 = value
		}
	}

	var result3 error
	if len(resp.ReturnValues) > 2 {
		if value, ok := resp.ReturnValues[2].(error); ok {
			result3 = value
		}
	}

	return result1, result2, result3
}

// newReaderMockReadMethod creates a typed method wrapper.
func newReaderMockReadMethod(dm *_imptest.DependencyMethod) *ReaderMockReadMethod {
	return &ReaderMockReadMethod{DependencyMethod: dm}
}
