// Code generated by impgen. DO NOT EDIT.
// impgen:hash:883d542d5bf10224

package transcript_test

import (
	transcript "github.com/toejough/engram/internal/transcript"
	_imptest "github.com/toejough/imptest"
)

type FinderImp struct {
	Find *FinderMockFindMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *FinderImpEventually
}

type FinderImpEventually struct {
	Find *FinderMockFindMethod
}

type FinderMockFindArgs struct {
	Dirs []string
}

type FinderMockFindCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *FinderMockFindCall) GetArgs() FinderMockFindArgs {
	raw := c.RawArgs()
	return FinderMockFindArgs{
		Dirs: raw[0].([]string),
	}
}

// Return specifies the typed values the mock should return.
func (c *FinderMockFindCall) Return(result0 []transcript.FileEntry, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type FinderMockFindMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *FinderMockFindMethod) ArgsEqual(dirs ...string) *FinderMockFindCall {
	callArgs := []any{}
	for _, v := range dirs {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.ArgsEqual(callArgs...)
	return &FinderMockFindCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *FinderMockFindMethod) ArgsShould(matchers ...any) *FinderMockFindCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &FinderMockFindCall{DependencyCall: call}
}

// MockFinder creates a mock Finder and returns (mock, expectation handle).
func MockFinder(t _imptest.TestReporter) (transcript.Finder, *FinderImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &FinderImp{
		Find: newFinderMockFindMethod(_imptest.NewDependencyMethod(ctrl, "Find")),
	}
	imp.Eventually = &FinderImpEventually{
		Find: newFinderMockFindMethod(_imptest.NewDependencyMethod(ctrl, "Find").AsEventually()),
	}
	mock := &mockFinderImpl{ctrl: ctrl}
	return mock, imp
}

type mockFinderImpl struct {
	ctrl *_imptest.Imp
}

// Find implements transcript.Finder.Find.
func (impl *mockFinderImpl) Find(dirs ...string) ([]transcript.FileEntry, error) {
	callArgs := []any{}
	for _, v := range dirs {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Find",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []transcript.FileEntry
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]transcript.FileEntry); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newFinderMockFindMethod creates a typed method wrapper.
func newFinderMockFindMethod(dm *_imptest.DependencyMethod) *FinderMockFindMethod {
	return &FinderMockFindMethod{DependencyMethod: dm}
}
