// Code generated by impgen. DO NOT EDIT.
// impgen:hash:def24ace52736fe9

package vaultgraph_test

import (
	vaultgraph "github.com/toejough/engram/internal/vaultgraph"
	_imptest "github.com/toejough/imptest"
)

type VaultFSImp struct {
	ListMD   *VaultFSMockListMDMethod
	ReadFile *VaultFSMockReadFileMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *VaultFSImpEventually
}

type VaultFSImpEventually struct {
	ListMD   *VaultFSMockListMDMethod
	ReadFile *VaultFSMockReadFileMethod
}

type VaultFSMockListMDArgs struct {
	Dir string
}

type VaultFSMockListMDCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *VaultFSMockListMDCall) GetArgs() VaultFSMockListMDArgs {
	raw := c.RawArgs()
	return VaultFSMockListMDArgs{
		Dir: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *VaultFSMockListMDCall) Return(result0 []string, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type VaultFSMockListMDMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *VaultFSMockListMDMethod) ArgsEqual(dir string) *VaultFSMockListMDCall {
	call := m.DependencyMethod.ArgsEqual(dir)
	return &VaultFSMockListMDCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *VaultFSMockListMDMethod) ArgsShould(matchers ...any) *VaultFSMockListMDCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &VaultFSMockListMDCall{DependencyCall: call}
}

type VaultFSMockReadFileArgs struct {
	Path string
}

type VaultFSMockReadFileCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *VaultFSMockReadFileCall) GetArgs() VaultFSMockReadFileArgs {
	raw := c.RawArgs()
	return VaultFSMockReadFileArgs{
		Path: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *VaultFSMockReadFileCall) Return(result0 []byte, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type VaultFSMockReadFileMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *VaultFSMockReadFileMethod) ArgsEqual(path string) *VaultFSMockReadFileCall {
	call := m.DependencyMethod.ArgsEqual(path)
	return &VaultFSMockReadFileCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *VaultFSMockReadFileMethod) ArgsShould(matchers ...any) *VaultFSMockReadFileCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &VaultFSMockReadFileCall{DependencyCall: call}
}

// MockVaultFS creates a mock VaultFS and returns (mock, expectation handle).
func MockVaultFS(t _imptest.TestReporter) (vaultgraph.VaultFS, *VaultFSImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &VaultFSImp{
		ListMD:   newVaultFSMockListMDMethod(_imptest.NewDependencyMethod(ctrl, "ListMD")),
		ReadFile: newVaultFSMockReadFileMethod(_imptest.NewDependencyMethod(ctrl, "ReadFile")),
	}
	imp.Eventually = &VaultFSImpEventually{
		ListMD:   newVaultFSMockListMDMethod(_imptest.NewDependencyMethod(ctrl, "ListMD").AsEventually()),
		ReadFile: newVaultFSMockReadFileMethod(_imptest.NewDependencyMethod(ctrl, "ReadFile").AsEventually()),
	}
	mock := &mockVaultFSImpl{ctrl: ctrl}
	return mock, imp
}

type mockVaultFSImpl struct {
	ctrl *_imptest.Imp
}

// ListMD implements vaultgraph.VaultFS.ListMD.
func (impl *mockVaultFSImpl) ListMD(dir string) ([]string, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ListMD",
		Args:         []any{dir},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]string); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// ReadFile implements vaultgraph.VaultFS.ReadFile.
func (impl *mockVaultFSImpl) ReadFile(path string) ([]byte, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReadFile",
		Args:         []any{path},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []byte
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]byte); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newVaultFSMockListMDMethod creates a typed method wrapper.
func newVaultFSMockListMDMethod(dm *_imptest.DependencyMethod) *VaultFSMockListMDMethod {
	return &VaultFSMockListMDMethod{DependencyMethod: dm}
}

// newVaultFSMockReadFileMethod creates a typed method wrapper.
func newVaultFSMockReadFileMethod(dm *_imptest.DependencyMethod) *VaultFSMockReadFileMethod {
	return &VaultFSMockReadFileMethod{DependencyMethod: dm}
}
