// Code generated by impgen. DO NOT EDIT.

package cli_test

import (
	context "context"
	io "io"

	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

type StartExportDoLearnCallHandle struct {
	*_imptest.CallableController[StartExportDoLearnReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *StartExportDoLearnCallHandleEventually
}

// PanicEquals verifies the function panics with the expected value.
func (h *StartExportDoLearnCallHandle) PanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}

		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// PanicShould verifies the function panics with a value matching the given matcher.
func (h *StartExportDoLearnCallHandle) PanicShould(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}

		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ReturnsEqual verifies the function returned the expected values.
func (h *StartExportDoLearnCallHandle) ReturnsEqual(v0 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}

		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ReturnsShould verifies the return values match the given matchers.
func (h *StartExportDoLearnCallHandle) ReturnsShould(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		ok, msg := _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}

		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

type StartExportDoLearnCallHandleEventually struct {
	h *StartExportDoLearnCallHandle
}

// PanicEquals registers an async expectation for a panic value.
func (e *StartExportDoLearnCallHandleEventually) PanicEquals(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ReturnsEqual registers an async expectation for return values.
func (e *StartExportDoLearnCallHandleEventually) ReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *StartExportDoLearnCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()

		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}

	return e.h.pendingCompletion
}

type StartExportDoLearnReturnsReturn struct {
	Result0 error
}

// StartExportDoLearn starts the wrapped function in a goroutine for testing.
func StartExportDoLearn(
	t _imptest.TestReporter,
	fn func(
		context.Context, API,
		string, string, string, string, string, string, string, string, string,
		io.Writer,
	) error,
	ctx context.Context,
	api API,
	from string,
	learnType string,
	situation string,
	behavior string,
	impact string,
	action string,
	subject string,
	predicate string,
	object string,
	stdout io.Writer,
) *StartExportDoLearnCallHandle {
	handle := &StartExportDoLearnCallHandle{
		CallableController: _imptest.NewCallableController[StartExportDoLearnReturnsReturn](t),
		controller:         _imptest.NewTargetController(t),
	}
	handle.Eventually = &StartExportDoLearnCallHandleEventually{h: handle}

	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()

		ret0 := fn(
			ctx, api, from, learnType, situation, behavior, impact,
			action, subject, predicate, object, stdout,
		)
		handle.ReturnChan <- StartExportDoLearnReturnsReturn{Result0: ret0}
	}()

	return handle
}
