// Code generated by impgen. DO NOT EDIT.
// impgen:hash:5f902ece4c102fc2

package cli_test

import (
	context "context"
	update "github.com/toejough/engram/internal/update"
	_imptest "github.com/toejough/imptest"
)

type CommanderImp struct {
	Run *CommanderMockRunMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *CommanderImpEventually
}

type CommanderImpEventually struct {
	Run *CommanderMockRunMethod
}

type CommanderMockRunArgs struct {
	Ctx  context.Context
	Dir  string
	Name string
	Args []string
}

type CommanderMockRunCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *CommanderMockRunCall) GetArgs() CommanderMockRunArgs {
	raw := c.RawArgs()
	return CommanderMockRunArgs{
		Ctx:  raw[0].(context.Context),
		Dir:  raw[1].(string),
		Name: raw[2].(string),
		Args: raw[3].([]string),
	}
}

// Return specifies the typed values the mock should return.
func (c *CommanderMockRunCall) Return(result0 []byte, result1 []byte, result2 error) {
	c.DependencyCall.Return(result0, result1, result2)
}

type CommanderMockRunMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *CommanderMockRunMethod) ArgsEqual(ctx context.Context, dir string, name string, args ...string) *CommanderMockRunCall {
	callArgs := []any{ctx, dir, name}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.ArgsEqual(callArgs...)
	return &CommanderMockRunCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *CommanderMockRunMethod) ArgsShould(matchers ...any) *CommanderMockRunCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &CommanderMockRunCall{DependencyCall: call}
}

// MockCommander creates a mock Commander and returns (mock, expectation handle).
func MockCommander(t _imptest.TestReporter) (update.Commander, *CommanderImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &CommanderImp{
		Run: newCommanderMockRunMethod(_imptest.NewDependencyMethod(ctrl, "Run")),
	}
	imp.Eventually = &CommanderImpEventually{
		Run: newCommanderMockRunMethod(_imptest.NewDependencyMethod(ctrl, "Run").AsEventually()),
	}
	mock := &mockCommanderImpl{ctrl: ctrl}
	return mock, imp
}

type mockCommanderImpl struct {
	ctrl *_imptest.Imp
}

// Run implements update.Commander.Run.
func (impl *mockCommanderImpl) Run(ctx context.Context, dir string, name string, args ...string) ([]byte, []byte, error) {
	callArgs := []any{ctx, dir, name}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Run",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []byte
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]byte); ok {
			result1 = value
		}
	}

	var result2 []byte
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].([]byte); ok {
			result2 = value
		}
	}

	var result3 error
	if len(resp.ReturnValues) > 2 {
		if value, ok := resp.ReturnValues[2].(error); ok {
			result3 = value
		}
	}

	return result1, result2, result3
}

// newCommanderMockRunMethod creates a typed method wrapper.
func newCommanderMockRunMethod(dm *_imptest.DependencyMethod) *CommanderMockRunMethod {
	return &CommanderMockRunMethod{DependencyMethod: dm}
}
