// Code generated by impgen. DO NOT EDIT.
// impgen:hash:68fbf1c32ef3f824

package cli_test

import (
	cli "github.com/toejough/engram/internal/cli"
	_imptest "github.com/toejough/imptest"
	fs "io/fs"
)

type SkillSourceFSImp struct {
	ReadDir  *SkillSourceFSMockReadDirMethod
	ReadFile *SkillSourceFSMockReadFileMethod
	Lstat    *SkillSourceFSMockLstatMethod
	Readlink *SkillSourceFSMockReadlinkMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *SkillSourceFSImpEventually
}

type SkillSourceFSImpEventually struct {
	ReadDir  *SkillSourceFSMockReadDirMethod
	ReadFile *SkillSourceFSMockReadFileMethod
	Lstat    *SkillSourceFSMockLstatMethod
	Readlink *SkillSourceFSMockReadlinkMethod
}

type SkillSourceFSMockLstatArgs struct {
	Path string
}

type SkillSourceFSMockLstatCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SkillSourceFSMockLstatCall) GetArgs() SkillSourceFSMockLstatArgs {
	raw := c.RawArgs()
	return SkillSourceFSMockLstatArgs{
		Path: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *SkillSourceFSMockLstatCall) Return(result0 fs.FileInfo, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type SkillSourceFSMockLstatMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *SkillSourceFSMockLstatMethod) ArgsEqual(path string) *SkillSourceFSMockLstatCall {
	call := m.DependencyMethod.ArgsEqual(path)
	return &SkillSourceFSMockLstatCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *SkillSourceFSMockLstatMethod) ArgsShould(matchers ...any) *SkillSourceFSMockLstatCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &SkillSourceFSMockLstatCall{DependencyCall: call}
}

type SkillSourceFSMockReadDirArgs struct {
	Path string
}

type SkillSourceFSMockReadDirCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SkillSourceFSMockReadDirCall) GetArgs() SkillSourceFSMockReadDirArgs {
	raw := c.RawArgs()
	return SkillSourceFSMockReadDirArgs{
		Path: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *SkillSourceFSMockReadDirCall) Return(result0 []fs.DirEntry, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type SkillSourceFSMockReadDirMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *SkillSourceFSMockReadDirMethod) ArgsEqual(path string) *SkillSourceFSMockReadDirCall {
	call := m.DependencyMethod.ArgsEqual(path)
	return &SkillSourceFSMockReadDirCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *SkillSourceFSMockReadDirMethod) ArgsShould(matchers ...any) *SkillSourceFSMockReadDirCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &SkillSourceFSMockReadDirCall{DependencyCall: call}
}

type SkillSourceFSMockReadFileArgs struct {
	Path string
}

type SkillSourceFSMockReadFileCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SkillSourceFSMockReadFileCall) GetArgs() SkillSourceFSMockReadFileArgs {
	raw := c.RawArgs()
	return SkillSourceFSMockReadFileArgs{
		Path: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *SkillSourceFSMockReadFileCall) Return(result0 []byte, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type SkillSourceFSMockReadFileMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *SkillSourceFSMockReadFileMethod) ArgsEqual(path string) *SkillSourceFSMockReadFileCall {
	call := m.DependencyMethod.ArgsEqual(path)
	return &SkillSourceFSMockReadFileCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *SkillSourceFSMockReadFileMethod) ArgsShould(matchers ...any) *SkillSourceFSMockReadFileCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &SkillSourceFSMockReadFileCall{DependencyCall: call}
}

type SkillSourceFSMockReadlinkArgs struct {
	Path string
}

type SkillSourceFSMockReadlinkCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SkillSourceFSMockReadlinkCall) GetArgs() SkillSourceFSMockReadlinkArgs {
	raw := c.RawArgs()
	return SkillSourceFSMockReadlinkArgs{
		Path: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *SkillSourceFSMockReadlinkCall) Return(result0 string, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type SkillSourceFSMockReadlinkMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *SkillSourceFSMockReadlinkMethod) ArgsEqual(path string) *SkillSourceFSMockReadlinkCall {
	call := m.DependencyMethod.ArgsEqual(path)
	return &SkillSourceFSMockReadlinkCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *SkillSourceFSMockReadlinkMethod) ArgsShould(matchers ...any) *SkillSourceFSMockReadlinkCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &SkillSourceFSMockReadlinkCall{DependencyCall: call}
}

// MockSkillSourceFS creates a mock SkillSourceFS and returns (mock, expectation handle).
func MockSkillSourceFS(t _imptest.TestReporter) (cli.SkillSourceFS, *SkillSourceFSImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &SkillSourceFSImp{
		ReadDir:  newSkillSourceFSMockReadDirMethod(_imptest.NewDependencyMethod(ctrl, "ReadDir")),
		ReadFile: newSkillSourceFSMockReadFileMethod(_imptest.NewDependencyMethod(ctrl, "ReadFile")),
		Lstat:    newSkillSourceFSMockLstatMethod(_imptest.NewDependencyMethod(ctrl, "Lstat")),
		Readlink: newSkillSourceFSMockReadlinkMethod(_imptest.NewDependencyMethod(ctrl, "Readlink")),
	}
	imp.Eventually = &SkillSourceFSImpEventually{
		ReadDir:  newSkillSourceFSMockReadDirMethod(_imptest.NewDependencyMethod(ctrl, "ReadDir").AsEventually()),
		ReadFile: newSkillSourceFSMockReadFileMethod(_imptest.NewDependencyMethod(ctrl, "ReadFile").AsEventually()),
		Lstat:    newSkillSourceFSMockLstatMethod(_imptest.NewDependencyMethod(ctrl, "Lstat").AsEventually()),
		Readlink: newSkillSourceFSMockReadlinkMethod(_imptest.NewDependencyMethod(ctrl, "Readlink").AsEventually()),
	}
	mock := &mockSkillSourceFSImpl{ctrl: ctrl}
	return mock, imp
}

type mockSkillSourceFSImpl struct {
	ctrl *_imptest.Imp
}

// Lstat implements cli.SkillSourceFS.Lstat.
func (impl *mockSkillSourceFSImpl) Lstat(path string) (fs.FileInfo, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Lstat",
		Args:         []any{path},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 fs.FileInfo
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(fs.FileInfo); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// ReadDir implements cli.SkillSourceFS.ReadDir.
func (impl *mockSkillSourceFSImpl) ReadDir(path string) ([]fs.DirEntry, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReadDir",
		Args:         []any{path},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []fs.DirEntry
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]fs.DirEntry); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// ReadFile implements cli.SkillSourceFS.ReadFile.
func (impl *mockSkillSourceFSImpl) ReadFile(path string) ([]byte, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReadFile",
		Args:         []any{path},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []byte
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]byte); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Readlink implements cli.SkillSourceFS.Readlink.
func (impl *mockSkillSourceFSImpl) Readlink(path string) (string, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Readlink",
		Args:         []any{path},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newSkillSourceFSMockLstatMethod creates a typed method wrapper.
func newSkillSourceFSMockLstatMethod(dm *_imptest.DependencyMethod) *SkillSourceFSMockLstatMethod {
	return &SkillSourceFSMockLstatMethod{DependencyMethod: dm}
}

// newSkillSourceFSMockReadDirMethod creates a typed method wrapper.
func newSkillSourceFSMockReadDirMethod(dm *_imptest.DependencyMethod) *SkillSourceFSMockReadDirMethod {
	return &SkillSourceFSMockReadDirMethod{DependencyMethod: dm}
}

// newSkillSourceFSMockReadFileMethod creates a typed method wrapper.
func newSkillSourceFSMockReadFileMethod(dm *_imptest.DependencyMethod) *SkillSourceFSMockReadFileMethod {
	return &SkillSourceFSMockReadFileMethod{DependencyMethod: dm}
}

// newSkillSourceFSMockReadlinkMethod creates a typed method wrapper.
func newSkillSourceFSMockReadlinkMethod(dm *_imptest.DependencyMethod) *SkillSourceFSMockReadlinkMethod {
	return &SkillSourceFSMockReadlinkMethod{DependencyMethod: dm}
}
