// Code generated by impgen. DO NOT EDIT.
// impgen:hash:47859d983f2194d6

package cli_test

import (
	context "context"
	_imptest "github.com/toejough/imptest"
)

type APIImp struct {
	PostMessage     *APIMockPostMessageMethod
	WaitForResponse *APIMockWaitForResponseMethod
	Subscribe       *APIMockSubscribeMethod
	Status          *APIMockStatusMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *APIImpEventually
}

type APIImpEventually struct {
	PostMessage     *APIMockPostMessageMethod
	WaitForResponse *APIMockWaitForResponseMethod
	Subscribe       *APIMockSubscribeMethod
	Status          *APIMockStatusMethod
}

type APIMockPostMessageArgs struct {
	Ctx context.Context
	Req PostMessageRequest
}

type APIMockPostMessageCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *APIMockPostMessageCall) GetArgs() APIMockPostMessageArgs {
	raw := c.RawArgs()
	return APIMockPostMessageArgs{
		Ctx: raw[0].(context.Context),
		Req: raw[1].(PostMessageRequest),
	}
}

// Return specifies the typed values the mock should return.
func (c *APIMockPostMessageCall) Return(result0 PostMessageResponse, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type APIMockPostMessageMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *APIMockPostMessageMethod) ArgsEqual(ctx context.Context, req PostMessageRequest) *APIMockPostMessageCall {
	call := m.DependencyMethod.ArgsEqual(ctx, req)
	return &APIMockPostMessageCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *APIMockPostMessageMethod) ArgsShould(matchers ...any) *APIMockPostMessageCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &APIMockPostMessageCall{DependencyCall: call}
}

type APIMockStatusArgs struct {
	Ctx context.Context
}

type APIMockStatusCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *APIMockStatusCall) GetArgs() APIMockStatusArgs {
	raw := c.RawArgs()
	return APIMockStatusArgs{
		Ctx: raw[0].(context.Context),
	}
}

// Return specifies the typed values the mock should return.
func (c *APIMockStatusCall) Return(result0 StatusResponse, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type APIMockStatusMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *APIMockStatusMethod) ArgsEqual(ctx context.Context) *APIMockStatusCall {
	call := m.DependencyMethod.ArgsEqual(ctx)
	return &APIMockStatusCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *APIMockStatusMethod) ArgsShould(matchers ...any) *APIMockStatusCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &APIMockStatusCall{DependencyCall: call}
}

type APIMockSubscribeArgs struct {
	Ctx context.Context
	Req SubscribeRequest
}

type APIMockSubscribeCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *APIMockSubscribeCall) GetArgs() APIMockSubscribeArgs {
	raw := c.RawArgs()
	return APIMockSubscribeArgs{
		Ctx: raw[0].(context.Context),
		Req: raw[1].(SubscribeRequest),
	}
}

// Return specifies the typed values the mock should return.
func (c *APIMockSubscribeCall) Return(result0 SubscribeResponse, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type APIMockSubscribeMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *APIMockSubscribeMethod) ArgsEqual(ctx context.Context, req SubscribeRequest) *APIMockSubscribeCall {
	call := m.DependencyMethod.ArgsEqual(ctx, req)
	return &APIMockSubscribeCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *APIMockSubscribeMethod) ArgsShould(matchers ...any) *APIMockSubscribeCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &APIMockSubscribeCall{DependencyCall: call}
}

type APIMockWaitForResponseArgs struct {
	Ctx context.Context
	Req WaitRequest
}

type APIMockWaitForResponseCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *APIMockWaitForResponseCall) GetArgs() APIMockWaitForResponseArgs {
	raw := c.RawArgs()
	return APIMockWaitForResponseArgs{
		Ctx: raw[0].(context.Context),
		Req: raw[1].(WaitRequest),
	}
}

// Return specifies the typed values the mock should return.
func (c *APIMockWaitForResponseCall) Return(result0 WaitResponse, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type APIMockWaitForResponseMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *APIMockWaitForResponseMethod) ArgsEqual(ctx context.Context, req WaitRequest) *APIMockWaitForResponseCall {
	call := m.DependencyMethod.ArgsEqual(ctx, req)
	return &APIMockWaitForResponseCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *APIMockWaitForResponseMethod) ArgsShould(matchers ...any) *APIMockWaitForResponseCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &APIMockWaitForResponseCall{DependencyCall: call}
}

// MockAPI creates a mock API and returns (mock, expectation handle).
func MockAPI(t _imptest.TestReporter) (API, *APIImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &APIImp{
		PostMessage:     newAPIMockPostMessageMethod(_imptest.NewDependencyMethod(ctrl, "PostMessage")),
		WaitForResponse: newAPIMockWaitForResponseMethod(_imptest.NewDependencyMethod(ctrl, "WaitForResponse")),
		Subscribe:       newAPIMockSubscribeMethod(_imptest.NewDependencyMethod(ctrl, "Subscribe")),
		Status:          newAPIMockStatusMethod(_imptest.NewDependencyMethod(ctrl, "Status")),
	}
	imp.Eventually = &APIImpEventually{
		PostMessage:     newAPIMockPostMessageMethod(_imptest.NewDependencyMethod(ctrl, "PostMessage").AsEventually()),
		WaitForResponse: newAPIMockWaitForResponseMethod(_imptest.NewDependencyMethod(ctrl, "WaitForResponse").AsEventually()),
		Subscribe:       newAPIMockSubscribeMethod(_imptest.NewDependencyMethod(ctrl, "Subscribe").AsEventually()),
		Status:          newAPIMockStatusMethod(_imptest.NewDependencyMethod(ctrl, "Status").AsEventually()),
	}
	mock := &mockAPIImpl{ctrl: ctrl}
	return mock, imp
}

type mockAPIImpl struct {
	ctrl *_imptest.Imp
}

// PostMessage implements API.PostMessage.
func (impl *mockAPIImpl) PostMessage(ctx context.Context, req PostMessageRequest) (PostMessageResponse, error) {
	call := &_imptest.GenericCall{
		MethodName:   "PostMessage",
		Args:         []any{ctx, req},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 PostMessageResponse
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(PostMessageResponse); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Status implements API.Status.
func (impl *mockAPIImpl) Status(ctx context.Context) (StatusResponse, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Status",
		Args:         []any{ctx},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 StatusResponse
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(StatusResponse); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Subscribe implements API.Subscribe.
func (impl *mockAPIImpl) Subscribe(ctx context.Context, req SubscribeRequest) (SubscribeResponse, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Subscribe",
		Args:         []any{ctx, req},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 SubscribeResponse
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(SubscribeResponse); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// WaitForResponse implements API.WaitForResponse.
func (impl *mockAPIImpl) WaitForResponse(ctx context.Context, req WaitRequest) (WaitResponse, error) {
	call := &_imptest.GenericCall{
		MethodName:   "WaitForResponse",
		Args:         []any{ctx, req},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 WaitResponse
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(WaitResponse); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newAPIMockPostMessageMethod creates a typed method wrapper.
func newAPIMockPostMessageMethod(dm *_imptest.DependencyMethod) *APIMockPostMessageMethod {
	return &APIMockPostMessageMethod{DependencyMethod: dm}
}

// newAPIMockStatusMethod creates a typed method wrapper.
func newAPIMockStatusMethod(dm *_imptest.DependencyMethod) *APIMockStatusMethod {
	return &APIMockStatusMethod{DependencyMethod: dm}
}

// newAPIMockSubscribeMethod creates a typed method wrapper.
func newAPIMockSubscribeMethod(dm *_imptest.DependencyMethod) *APIMockSubscribeMethod {
	return &APIMockSubscribeMethod{DependencyMethod: dm}
}

// newAPIMockWaitForResponseMethod creates a typed method wrapper.
func newAPIMockWaitForResponseMethod(dm *_imptest.DependencyMethod) *APIMockWaitForResponseMethod {
	return &APIMockWaitForResponseMethod{DependencyMethod: dm}
}
