// Code generated by impgen. DO NOT EDIT.

package cli_test

import (
	context "context"
	io "io"

	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

type StartExportDoSubscribeCallHandle struct {
	*_imptest.CallableController[StartExportDoSubscribeReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *StartExportDoSubscribeCallHandleEventually
}

// PanicEquals verifies the function panics with the expected value.
func (h *StartExportDoSubscribeCallHandle) PanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}

		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// PanicShould verifies the function panics with a value matching the given matcher.
func (h *StartExportDoSubscribeCallHandle) PanicShould(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}

		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ReturnsEqual verifies the function returned the expected values.
func (h *StartExportDoSubscribeCallHandle) ReturnsEqual(v0 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}

		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ReturnsShould verifies the return values match the given matchers.
func (h *StartExportDoSubscribeCallHandle) ReturnsShould(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		ok, msg := _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}

		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

type StartExportDoSubscribeCallHandleEventually struct {
	h *StartExportDoSubscribeCallHandle
}

// PanicEquals registers an async expectation for a panic value.
func (e *StartExportDoSubscribeCallHandleEventually) PanicEquals(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ReturnsEqual registers an async expectation for return values.
func (e *StartExportDoSubscribeCallHandleEventually) ReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *StartExportDoSubscribeCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()

		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}

	return e.h.pendingCompletion
}

type StartExportDoSubscribeReturnsReturn struct {
	Result0 error
}

// StartExportDoSubscribe starts the wrapped function in a goroutine for testing.
func StartExportDoSubscribe(
	t _imptest.TestReporter,
	fn func(context.Context, API, string, int, io.Writer) error,
	ctx context.Context,
	api API,
	agent string,
	afterCursor int,
	stdout io.Writer,
) *StartExportDoSubscribeCallHandle {
	handle := &StartExportDoSubscribeCallHandle{
		CallableController: _imptest.NewCallableController[StartExportDoSubscribeReturnsReturn](t),
		controller:         _imptest.NewTargetController(t),
	}
	handle.Eventually = &StartExportDoSubscribeCallHandleEventually{h: handle}

	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()

		ret0 := fn(ctx, api, agent, afterCursor, stdout)
		handle.ReturnChan <- StartExportDoSubscribeReturnsReturn{Result0: ret0}
	}()

	return handle
}
