package main

import "github.com/toejough/targ"

func main() {
	targ.Main(
		targ.Group("state",
			targ.Targ(stateInit).Name("init").Description("Initialize project state file"),
			targ.Targ(stateGet).Name("get").Description("Get current project state"),
			targ.Targ(stateTransition).Name("transition").Description("Transition to a new state"),
		),
		targ.Group("log",
			targ.Targ(logWrite).Name("write").Description("Write an entry to the project log"),
		),
		targ.Group("config",
			targ.Targ(configInit).Name("init").Description("Initialize project configuration"),
			targ.Targ(configGet).Name("get").Description("Get configuration value"),
			targ.Targ(configPath).Name("path").Description("Show configuration file path"),
		),
		targ.Group("coverage",
			targ.Targ(coverageAnalyze).Name("analyze").Description("Analyze test coverage data"),
			targ.Targ(coverageReport).Name("report").Description("Generate coverage report"),
		),
		targ.Group("trace",
			targ.Targ(traceValidateArtifacts).Name("validate").Description("Validate traceability by scanning artifact **Traces to:** fields"),
			targ.Targ(traceRepair).Name("repair").Description("Detect and report traceability issues in artifacts"),
		),
		targ.Group("conflict",
			targ.Targ(conflictCreate).Name("create").Description("Create a conflict record"),
			targ.Targ(conflictCheck).Name("check").Description("Check for unresolved conflicts"),
			targ.Targ(conflictList).Name("list").Description("List all conflicts"),
		),
		targ.Group("context",
			targ.Targ(contextWrite).Name("write").Description("Write context for handoff"),
			targ.Targ(contextRead).Name("read").Description("Read saved context"),
		),
		targ.Group("screenshot",
			targ.Targ(screenshotDiff).Name("diff").Description("Compare screenshots for visual differences"),
		),
		targ.Group("integrate",
			targ.Targ(integrateMerge).Name("merge").Description("Merge per-project docs into top-level"),
			targ.Targ(integrateFeatures).Name("features").Description("Merge feature-specific docs (design-*.md) into top-level"),
			targ.Targ(integrateCleanup).Name("cleanup").Description("Clean up after integration"),
		),
		targ.Group("escalation",
			targ.Targ(escalationWrite).Name("write").Description("Write an escalation record"),
			targ.Targ(escalationReview).Name("review").Description("Review pending escalations"),
			targ.Targ(escalationList).Name("list").Description("List all escalations"),
			targ.Targ(escalationResolve).Name("resolve").Description("Resolve an escalation by ID"),
		),
		targ.Group("skills",
			targ.Targ(skillsInstall).Name("install").Description("Install skills by creating symlinks"),
			targ.Targ(skillsStatus).Name("status").Description("Show skill installation status"),
			targ.Targ(skillsUninstall).Name("uninstall").Description("Uninstall skills by removing symlinks"),
		),
	)
}
