package main

import "github.com/toejough/targ"

func main() {
	targ.Main(
		targ.Group("state",
			targ.Targ(stateInit).Name("init"),
			targ.Targ(stateGet).Name("get"),
			targ.Targ(stateTransition).Name("transition"),
		),
		targ.Group("log",
			targ.Targ(logWrite).Name("write"),
		),
		targ.Group("config",
			targ.Targ(configInit).Name("init"),
			targ.Targ(configGet).Name("get"),
			targ.Targ(configPath).Name("path"),
		),
		targ.Group("coverage",
			targ.Targ(coverageAnalyze).Name("analyze"),
			targ.Targ(coverageReport).Name("report"),
		),
		targ.Group("trace",
			targ.Targ(traceAdd).Name("add"),
			targ.Targ(traceValidate).Name("validate"),
			targ.Targ(traceValidateV2).Name("validate-v2"),
			targ.Targ(traceImpact).Name("impact"),
		),
		targ.Group("conflict",
			targ.Targ(conflictCreate).Name("create"),
			targ.Targ(conflictCheck).Name("check"),
			targ.Targ(conflictList).Name("list"),
		),
		targ.Group("context",
			targ.Targ(contextWrite).Name("write"),
			targ.Targ(contextRead).Name("read"),
		),
		targ.Group("screenshot",
			targ.Targ(screenshotDiff).Name("diff"),
		),
		targ.Group("integrate",
			targ.Targ(integrateMerge).Name("merge"),
			targ.Targ(integrateCleanup).Name("cleanup"),
		),
		targ.Group("escalation",
			targ.Targ(escalationWrite).Name("write"),
			targ.Targ(escalationReview).Name("review"),
			targ.Targ(escalationList).Name("list"),
		),
	)
}
