// Code generated by impgen. DO NOT EDIT.
// impgen:hash:7b121d388ff5ee39

package extract_test

import (
	extract "engram/internal/extract"
	_imptest "github.com/toejough/imptest"
)

type SessionOverlapsImp struct {
	HasOverlap *SessionOverlapsMockHasOverlapMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *SessionOverlapsImpEventually
}

type SessionOverlapsImpEventually struct {
	HasOverlap *SessionOverlapsMockHasOverlapMethod
}

type SessionOverlapsMockHasOverlapArgs struct {
	Content string
}

type SessionOverlapsMockHasOverlapCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SessionOverlapsMockHasOverlapCall) GetArgs() SessionOverlapsMockHasOverlapArgs {
	raw := c.RawArgs()
	return SessionOverlapsMockHasOverlapArgs{
		Content: raw[0].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *SessionOverlapsMockHasOverlapCall) Return(result0 bool) {
	c.DependencyCall.Return(result0)
}

type SessionOverlapsMockHasOverlapMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *SessionOverlapsMockHasOverlapMethod) ArgsEqual(content string) *SessionOverlapsMockHasOverlapCall {
	call := m.DependencyMethod.ArgsEqual(content)
	return &SessionOverlapsMockHasOverlapCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *SessionOverlapsMockHasOverlapMethod) ArgsShould(matchers ...any) *SessionOverlapsMockHasOverlapCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &SessionOverlapsMockHasOverlapCall{DependencyCall: call}
}

// MockSessionOverlaps creates a mock SessionOverlaps and returns (mock, expectation handle).
func MockSessionOverlaps(t _imptest.TestReporter) (extract.SessionOverlaps, *SessionOverlapsImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &SessionOverlapsImp{
		HasOverlap: newSessionOverlapsMockHasOverlapMethod(_imptest.NewDependencyMethod(ctrl, "HasOverlap")),
	}
	imp.Eventually = &SessionOverlapsImpEventually{
		HasOverlap: newSessionOverlapsMockHasOverlapMethod(_imptest.NewDependencyMethod(ctrl, "HasOverlap").AsEventually()),
	}
	mock := &mockSessionOverlapsImpl{ctrl: ctrl}
	return mock, imp
}

type mockSessionOverlapsImpl struct {
	ctrl *_imptest.Imp
}

// HasOverlap implements extract.SessionOverlaps.HasOverlap.
func (impl *mockSessionOverlapsImpl) HasOverlap(content string) bool {
	call := &_imptest.GenericCall{
		MethodName:   "HasOverlap",
		Args:         []any{content},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 bool
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(bool); ok {
			result1 = value
		}
	}

	return result1
}

// newSessionOverlapsMockHasOverlapMethod creates a typed method wrapper.
func newSessionOverlapsMockHasOverlapMethod(dm *_imptest.DependencyMethod) *SessionOverlapsMockHasOverlapMethod {
	return &SessionOverlapsMockHasOverlapMethod{DependencyMethod: dm}
}
