// Code generated by impgen. DO NOT EDIT.
// impgen:hash:50762193a5a0ba90

package extract_test

import (
	context "context"
	extract "engram/internal/extract"
	_imptest "github.com/toejough/imptest"
)

type EnricherImp struct {
	Enrich *EnricherMockEnrichMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *EnricherImpEventually
}

type EnricherImpEventually struct {
	Enrich *EnricherMockEnrichMethod
}

type EnricherMockEnrichArgs struct {
	Ctx        context.Context
	Transcript []byte
}

type EnricherMockEnrichCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *EnricherMockEnrichCall) GetArgs() EnricherMockEnrichArgs {
	raw := c.RawArgs()
	return EnricherMockEnrichArgs{
		Ctx:        raw[0].(context.Context),
		Transcript: raw[1].([]byte),
	}
}

// Return specifies the typed values the mock should return.
func (c *EnricherMockEnrichCall) Return(result0 []extract.RawLearning, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type EnricherMockEnrichMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *EnricherMockEnrichMethod) ArgsEqual(ctx context.Context, transcript []byte) *EnricherMockEnrichCall {
	call := m.DependencyMethod.ArgsEqual(ctx, transcript)
	return &EnricherMockEnrichCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *EnricherMockEnrichMethod) ArgsShould(matchers ...any) *EnricherMockEnrichCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &EnricherMockEnrichCall{DependencyCall: call}
}

// MockEnricher creates a mock Enricher and returns (mock, expectation handle).
func MockEnricher(t _imptest.TestReporter) (extract.Enricher, *EnricherImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &EnricherImp{
		Enrich: newEnricherMockEnrichMethod(_imptest.NewDependencyMethod(ctrl, "Enrich")),
	}
	imp.Eventually = &EnricherImpEventually{
		Enrich: newEnricherMockEnrichMethod(_imptest.NewDependencyMethod(ctrl, "Enrich").AsEventually()),
	}
	mock := &mockEnricherImpl{ctrl: ctrl}
	return mock, imp
}

type mockEnricherImpl struct {
	ctrl *_imptest.Imp
}

// Enrich implements extract.Enricher.Enrich.
func (impl *mockEnricherImpl) Enrich(ctx context.Context, transcript []byte) ([]extract.RawLearning, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Enrich",
		Args:         []any{ctx, transcript},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []extract.RawLearning
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]extract.RawLearning); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newEnricherMockEnrichMethod creates a typed method wrapper.
func newEnricherMockEnrichMethod(dm *_imptest.DependencyMethod) *EnricherMockEnrichMethod {
	return &EnricherMockEnrichMethod{DependencyMethod: dm}
}
