// Code generated by impgen. DO NOT EDIT.
// impgen:hash:1c07f0e6c926317c

package extract_test

import (
	context "context"
	extract "engram/internal/extract"
	_imptest "github.com/toejough/imptest"
)

type ClassifierImp struct {
	Classify *ClassifierMockClassifyMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *ClassifierImpEventually
}

type ClassifierImpEventually struct {
	Classify *ClassifierMockClassifyMethod
}

type ClassifierMockClassifyArgs struct {
	Ctx        context.Context
	Learning   extract.RawLearning
	Transcript []byte
}

type ClassifierMockClassifyCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ClassifierMockClassifyCall) GetArgs() ClassifierMockClassifyArgs {
	raw := c.RawArgs()
	return ClassifierMockClassifyArgs{
		Ctx:        raw[0].(context.Context),
		Learning:   raw[1].(extract.RawLearning),
		Transcript: raw[2].([]byte),
	}
}

// Return specifies the typed values the mock should return.
func (c *ClassifierMockClassifyCall) Return(result0 string, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type ClassifierMockClassifyMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *ClassifierMockClassifyMethod) ArgsEqual(ctx context.Context, learning extract.RawLearning, transcript []byte) *ClassifierMockClassifyCall {
	call := m.DependencyMethod.ArgsEqual(ctx, learning, transcript)
	return &ClassifierMockClassifyCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *ClassifierMockClassifyMethod) ArgsShould(matchers ...any) *ClassifierMockClassifyCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &ClassifierMockClassifyCall{DependencyCall: call}
}

// MockClassifier creates a mock Classifier and returns (mock, expectation handle).
func MockClassifier(t _imptest.TestReporter) (extract.Classifier, *ClassifierImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &ClassifierImp{
		Classify: newClassifierMockClassifyMethod(_imptest.NewDependencyMethod(ctrl, "Classify")),
	}
	imp.Eventually = &ClassifierImpEventually{
		Classify: newClassifierMockClassifyMethod(_imptest.NewDependencyMethod(ctrl, "Classify").AsEventually()),
	}
	mock := &mockClassifierImpl{ctrl: ctrl}
	return mock, imp
}

type mockClassifierImpl struct {
	ctrl *_imptest.Imp
}

// Classify implements extract.Classifier.Classify.
func (impl *mockClassifierImpl) Classify(ctx context.Context, learning extract.RawLearning, transcript []byte) (string, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Classify",
		Args:         []any{ctx, learning, transcript},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newClassifierMockClassifyMethod creates a typed method wrapper.
func newClassifierMockClassifyMethod(dm *_imptest.DependencyMethod) *ClassifierMockClassifyMethod {
	return &ClassifierMockClassifyMethod{DependencyMethod: dm}
}
