// Code generated by impgen. DO NOT EDIT.
// impgen:hash:7e63207609dae552

package correct_test

import (
	context "context"
	correct "engram/internal/correct"
	_imptest "github.com/toejough/imptest"
)

type ReclassifierImp struct {
	Reclassify *ReclassifierMockReclassifyMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *ReclassifierImpEventually
}

type ReclassifierImpEventually struct {
	Reclassify *ReclassifierMockReclassifyMethod
}

type ReclassifierMockReclassifyArgs struct {
	Ctx context.Context
}

type ReclassifierMockReclassifyCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ReclassifierMockReclassifyCall) GetArgs() ReclassifierMockReclassifyArgs {
	raw := c.RawArgs()
	return ReclassifierMockReclassifyArgs{
		Ctx: raw[0].(context.Context),
	}
}

// Return specifies the typed values the mock should return.
func (c *ReclassifierMockReclassifyCall) Return(result0 int, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type ReclassifierMockReclassifyMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *ReclassifierMockReclassifyMethod) ArgsEqual(ctx context.Context) *ReclassifierMockReclassifyCall {
	call := m.DependencyMethod.ArgsEqual(ctx)
	return &ReclassifierMockReclassifyCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *ReclassifierMockReclassifyMethod) ArgsShould(matchers ...any) *ReclassifierMockReclassifyCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &ReclassifierMockReclassifyCall{DependencyCall: call}
}

// MockReclassifier creates a mock Reclassifier and returns (mock, expectation handle).
func MockReclassifier(t _imptest.TestReporter) (correct.Reclassifier, *ReclassifierImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &ReclassifierImp{
		Reclassify: newReclassifierMockReclassifyMethod(_imptest.NewDependencyMethod(ctrl, "Reclassify")),
	}
	imp.Eventually = &ReclassifierImpEventually{
		Reclassify: newReclassifierMockReclassifyMethod(_imptest.NewDependencyMethod(ctrl, "Reclassify").AsEventually()),
	}
	mock := &mockReclassifierImpl{ctrl: ctrl}
	return mock, imp
}

type mockReclassifierImpl struct {
	ctrl *_imptest.Imp
}

// Reclassify implements correct.Reclassifier.Reclassify.
func (impl *mockReclassifierImpl) Reclassify(ctx context.Context) (int, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Reclassify",
		Args:         []any{ctx},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newReclassifierMockReclassifyMethod creates a typed method wrapper.
func newReclassifierMockReclassifyMethod(dm *_imptest.DependencyMethod) *ReclassifierMockReclassifyMethod {
	return &ReclassifierMockReclassifyMethod{DependencyMethod: dm}
}
