// Code generated by impgen. DO NOT EDIT.
// impgen:hash:236ce94e92712e24

package correct_test

import (
	context "context"
	corpus "engram/internal/corpus"
	correct "engram/internal/correct"
	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

type StartDetectCorrectionCallHandle struct {
	*_imptest.CallableController[StartDetectCorrectionReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *StartDetectCorrectionCallHandleEventually
}

// PanicEquals verifies the function panics with the expected value.
func (h *StartDetectCorrectionCallHandle) PanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// PanicShould verifies the function panics with a value matching the given matcher.
func (h *StartDetectCorrectionCallHandle) PanicShould(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ReturnsEqual verifies the function returned the expected values.
func (h *StartDetectCorrectionCallHandle) ReturnsEqual(v0 string, v1 []correct.Recording, v2 string, v3 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		if !_reflect.DeepEqual(h.Returned.Result1, v1) {
			h.T.Fatalf("expected return value 1 to be %v, got %v", v1, h.Returned.Result1)
		}
		if !_reflect.DeepEqual(h.Returned.Result2, v2) {
			h.T.Fatalf("expected return value 2 to be %v, got %v", v2, h.Returned.Result2)
		}
		if !_reflect.DeepEqual(h.Returned.Result3, v3) {
			h.T.Fatalf("expected return value 3 to be %v, got %v", v3, h.Returned.Result3)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ReturnsShould verifies the return values match the given matchers.
func (h *StartDetectCorrectionCallHandle) ReturnsShould(v0 any, v1 any, v2 any, v3 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		ok, msg = _imptest.MatchValue(h.Returned.Result1, v1)
		if !ok {
			h.T.Fatalf("return value 1: %s", msg)
		}
		ok, msg = _imptest.MatchValue(h.Returned.Result2, v2)
		if !ok {
			h.T.Fatalf("return value 2: %s", msg)
		}
		ok, msg = _imptest.MatchValue(h.Returned.Result3, v3)
		if !ok {
			h.T.Fatalf("return value 3: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

type StartDetectCorrectionCallHandleEventually struct {
	h *StartDetectCorrectionCallHandle
}

// PanicEquals registers an async expectation for a panic value.
func (e *StartDetectCorrectionCallHandleEventually) PanicEquals(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ReturnsEqual registers an async expectation for return values.
func (e *StartDetectCorrectionCallHandleEventually) ReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *StartDetectCorrectionCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

type StartDetectCorrectionReturnsReturn struct {
	Result0 string
	Result1 []correct.Recording
	Result2 string
	Result3 error
}

// StartDetectCorrection starts the wrapped function in a goroutine for testing.
func StartDetectCorrection(t _imptest.TestReporter, fn func(context.Context, correct.Reconciler, *corpus.Corpus, string) (string, []correct.Recording, string, error), ctx context.Context, reconciler correct.Reconciler, patterns *corpus.Corpus, message string) *StartDetectCorrectionCallHandle {
	handle := &StartDetectCorrectionCallHandle{
		CallableController: _imptest.NewCallableController[StartDetectCorrectionReturnsReturn](t),
		controller:         _imptest.NewTargetController(t),
	}
	handle.Eventually = &StartDetectCorrectionCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0, ret1, ret2, ret3 := fn(ctx, reconciler, patterns, message)
		handle.ReturnChan <- StartDetectCorrectionReturnsReturn{Result0: ret0, Result1: ret1, Result2: ret2, Result3: ret3}
	}()
	return handle
}
