// Code generated by impgen. DO NOT EDIT.
// impgen:hash:a67ac5e1e44e952b

package correct_test

import (
	context "context"
	correct "engram/internal/correct"
	_imptest "github.com/toejough/imptest"
)

type ReconcilerImp struct {
	Reconcile *ReconcilerMockReconcileMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *ReconcilerImpEventually
}

type ReconcilerImpEventually struct {
	Reconcile *ReconcilerMockReconcileMethod
}

type ReconcilerMockReconcileArgs struct {
	Ctx context.Context
	L   correct.Learning
}

type ReconcilerMockReconcileCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ReconcilerMockReconcileCall) GetArgs() ReconcilerMockReconcileArgs {
	raw := c.RawArgs()
	return ReconcilerMockReconcileArgs{
		Ctx: raw[0].(context.Context),
		L:   raw[1].(correct.Learning),
	}
}

// Return specifies the typed values the mock should return.
func (c *ReconcilerMockReconcileCall) Return(result0 correct.ReconcileResult, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type ReconcilerMockReconcileMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *ReconcilerMockReconcileMethod) ArgsEqual(ctx context.Context, l correct.Learning) *ReconcilerMockReconcileCall {
	call := m.DependencyMethod.ArgsEqual(ctx, l)
	return &ReconcilerMockReconcileCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *ReconcilerMockReconcileMethod) ArgsShould(matchers ...any) *ReconcilerMockReconcileCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &ReconcilerMockReconcileCall{DependencyCall: call}
}

// MockReconciler creates a mock Reconciler and returns (mock, expectation handle).
func MockReconciler(t _imptest.TestReporter) (correct.Reconciler, *ReconcilerImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &ReconcilerImp{
		Reconcile: newReconcilerMockReconcileMethod(_imptest.NewDependencyMethod(ctrl, "Reconcile")),
	}
	imp.Eventually = &ReconcilerImpEventually{
		Reconcile: newReconcilerMockReconcileMethod(_imptest.NewDependencyMethod(ctrl, "Reconcile").AsEventually()),
	}
	mock := &mockReconcilerImpl{ctrl: ctrl}
	return mock, imp
}

type mockReconcilerImpl struct {
	ctrl *_imptest.Imp
}

// Reconcile implements correct.Reconciler.Reconcile.
func (impl *mockReconcilerImpl) Reconcile(ctx context.Context, l correct.Learning) (correct.ReconcileResult, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Reconcile",
		Args:         []any{ctx, l},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 correct.ReconcileResult
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(correct.ReconcileResult); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newReconcilerMockReconcileMethod creates a typed method wrapper.
func newReconcilerMockReconcileMethod(dm *_imptest.DependencyMethod) *ReconcilerMockReconcileMethod {
	return &ReconcilerMockReconcileMethod{DependencyMethod: dm}
}
