// Code generated by impgen. DO NOT EDIT.
// impgen:hash:7bb0d6819e5e8143

package reclassify_test

import (
	context "context"
	reclassify "engram/internal/reclassify"
	_imptest "github.com/toejough/imptest"
)

type StoreImp struct {
	GetSessionSurfacings *StoreMockGetSessionSurfacingsMethod
	DecreaseImpact       *StoreMockDecreaseImpactMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *StoreImpEventually
}

type StoreImpEventually struct {
	GetSessionSurfacings *StoreMockGetSessionSurfacingsMethod
	DecreaseImpact       *StoreMockDecreaseImpactMethod
}

type StoreMockDecreaseImpactArgs struct {
	Ctx      context.Context
	MemoryID string
	Factor   float64
}

type StoreMockDecreaseImpactCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *StoreMockDecreaseImpactCall) GetArgs() StoreMockDecreaseImpactArgs {
	raw := c.RawArgs()
	return StoreMockDecreaseImpactArgs{
		Ctx:      raw[0].(context.Context),
		MemoryID: raw[1].(string),
		Factor:   raw[2].(float64),
	}
}

// Return specifies the typed values the mock should return.
func (c *StoreMockDecreaseImpactCall) Return(result0 error) {
	c.DependencyCall.Return(result0)
}

type StoreMockDecreaseImpactMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *StoreMockDecreaseImpactMethod) ArgsEqual(ctx context.Context, memoryID string, factor float64) *StoreMockDecreaseImpactCall {
	call := m.DependencyMethod.ArgsEqual(ctx, memoryID, factor)
	return &StoreMockDecreaseImpactCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *StoreMockDecreaseImpactMethod) ArgsShould(matchers ...any) *StoreMockDecreaseImpactCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &StoreMockDecreaseImpactCall{DependencyCall: call}
}

type StoreMockGetSessionSurfacingsArgs struct {
	Ctx context.Context
}

type StoreMockGetSessionSurfacingsCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *StoreMockGetSessionSurfacingsCall) GetArgs() StoreMockGetSessionSurfacingsArgs {
	raw := c.RawArgs()
	return StoreMockGetSessionSurfacingsArgs{
		Ctx: raw[0].(context.Context),
	}
}

// Return specifies the typed values the mock should return.
func (c *StoreMockGetSessionSurfacingsCall) Return(result0 []string, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type StoreMockGetSessionSurfacingsMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *StoreMockGetSessionSurfacingsMethod) ArgsEqual(ctx context.Context) *StoreMockGetSessionSurfacingsCall {
	call := m.DependencyMethod.ArgsEqual(ctx)
	return &StoreMockGetSessionSurfacingsCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *StoreMockGetSessionSurfacingsMethod) ArgsShould(matchers ...any) *StoreMockGetSessionSurfacingsCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &StoreMockGetSessionSurfacingsCall{DependencyCall: call}
}

// MockStore creates a mock Store and returns (mock, expectation handle).
func MockStore(t _imptest.TestReporter) (reclassify.Store, *StoreImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &StoreImp{
		GetSessionSurfacings: newStoreMockGetSessionSurfacingsMethod(_imptest.NewDependencyMethod(ctrl, "GetSessionSurfacings")),
		DecreaseImpact:       newStoreMockDecreaseImpactMethod(_imptest.NewDependencyMethod(ctrl, "DecreaseImpact")),
	}
	imp.Eventually = &StoreImpEventually{
		GetSessionSurfacings: newStoreMockGetSessionSurfacingsMethod(_imptest.NewDependencyMethod(ctrl, "GetSessionSurfacings").AsEventually()),
		DecreaseImpact:       newStoreMockDecreaseImpactMethod(_imptest.NewDependencyMethod(ctrl, "DecreaseImpact").AsEventually()),
	}
	mock := &mockStoreImpl{ctrl: ctrl}
	return mock, imp
}

type mockStoreImpl struct {
	ctrl *_imptest.Imp
}

// DecreaseImpact implements reclassify.Store.DecreaseImpact.
func (impl *mockStoreImpl) DecreaseImpact(ctx context.Context, memoryID string, factor float64) error {
	call := &_imptest.GenericCall{
		MethodName:   "DecreaseImpact",
		Args:         []any{ctx, memoryID, factor},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// GetSessionSurfacings implements reclassify.Store.GetSessionSurfacings.
func (impl *mockStoreImpl) GetSessionSurfacings(ctx context.Context) ([]string, error) {
	call := &_imptest.GenericCall{
		MethodName:   "GetSessionSurfacings",
		Args:         []any{ctx},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]string); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newStoreMockDecreaseImpactMethod creates a typed method wrapper.
func newStoreMockDecreaseImpactMethod(dm *_imptest.DependencyMethod) *StoreMockDecreaseImpactMethod {
	return &StoreMockDecreaseImpactMethod{DependencyMethod: dm}
}

// newStoreMockGetSessionSurfacingsMethod creates a typed method wrapper.
func newStoreMockGetSessionSurfacingsMethod(dm *_imptest.DependencyMethod) *StoreMockGetSessionSurfacingsMethod {
	return &StoreMockGetSessionSurfacingsMethod{DependencyMethod: dm}
}
