// Code generated by impgen. DO NOT EDIT.
// impgen:hash:200938da73f3e9de

package reconcile_test

import (
	context "context"
	reconcile "engram/internal/reconcile"
	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

type StartRunCallHandle struct {
	*_imptest.CallableController[StartRunReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *StartRunCallHandleEventually
}

// PanicEquals verifies the function panics with the expected value.
func (h *StartRunCallHandle) PanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// PanicShould verifies the function panics with a value matching the given matcher.
func (h *StartRunCallHandle) PanicShould(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ReturnsEqual verifies the function returned the expected values.
func (h *StartRunCallHandle) ReturnsEqual(v0 reconcile.Result, v1 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		if !_reflect.DeepEqual(h.Returned.Result1, v1) {
			h.T.Fatalf("expected return value 1 to be %v, got %v", v1, h.Returned.Result1)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ReturnsShould verifies the return values match the given matchers.
func (h *StartRunCallHandle) ReturnsShould(v0 any, v1 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		ok, msg = _imptest.MatchValue(h.Returned.Result1, v1)
		if !ok {
			h.T.Fatalf("return value 1: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

type StartRunCallHandleEventually struct {
	h *StartRunCallHandle
}

// PanicEquals registers an async expectation for a panic value.
func (e *StartRunCallHandleEventually) PanicEquals(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ReturnsEqual registers an async expectation for return values.
func (e *StartRunCallHandleEventually) ReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *StartRunCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

type StartRunReturnsReturn struct {
	Result0 reconcile.Result
	Result1 error
}

// StartRun starts the wrapped function in a goroutine for testing.
func StartRun(t _imptest.TestReporter, fn func(context.Context, reconcile.Store, reconcile.OverlapGate, int, reconcile.Learning) (reconcile.Result, error), ctx context.Context, s reconcile.Store, gate reconcile.OverlapGate, k int, l reconcile.Learning) *StartRunCallHandle {
	handle := &StartRunCallHandle{
		CallableController: _imptest.NewCallableController[StartRunReturnsReturn](t),
		controller:         _imptest.NewTargetController(t),
	}
	handle.Eventually = &StartRunCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0, ret1 := fn(ctx, s, gate, k, l)
		handle.ReturnChan <- StartRunReturnsReturn{Result0: ret0, Result1: ret1}
	}()
	return handle
}
