// Code generated by impgen. DO NOT EDIT.
// impgen:hash:6ba6e3d4be97b3f9

package reconcile_test

import (
	context "context"
	reconcile "engram/internal/reconcile"
	store "engram/internal/store"
	_imptest "github.com/toejough/imptest"
)

type OverlapGateImp struct {
	Check *OverlapGateMockCheckMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *OverlapGateImpEventually
}

type OverlapGateImpEventually struct {
	Check *OverlapGateMockCheckMethod
}

type OverlapGateMockCheckArgs struct {
	Ctx       context.Context
	Learning  reconcile.Learning
	Candidate store.Memory
}

type OverlapGateMockCheckCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *OverlapGateMockCheckCall) GetArgs() OverlapGateMockCheckArgs {
	raw := c.RawArgs()
	return OverlapGateMockCheckArgs{
		Ctx:       raw[0].(context.Context),
		Learning:  raw[1].(reconcile.Learning),
		Candidate: raw[2].(store.Memory),
	}
}

// Return specifies the typed values the mock should return.
func (c *OverlapGateMockCheckCall) Return(result0 bool, result1 string, result2 error) {
	c.DependencyCall.Return(result0, result1, result2)
}

type OverlapGateMockCheckMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *OverlapGateMockCheckMethod) ArgsEqual(ctx context.Context, learning reconcile.Learning, candidate store.Memory) *OverlapGateMockCheckCall {
	call := m.DependencyMethod.ArgsEqual(ctx, learning, candidate)
	return &OverlapGateMockCheckCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *OverlapGateMockCheckMethod) ArgsShould(matchers ...any) *OverlapGateMockCheckCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &OverlapGateMockCheckCall{DependencyCall: call}
}

// MockOverlapGate creates a mock OverlapGate and returns (mock, expectation handle).
func MockOverlapGate(t _imptest.TestReporter) (reconcile.OverlapGate, *OverlapGateImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &OverlapGateImp{
		Check: newOverlapGateMockCheckMethod(_imptest.NewDependencyMethod(ctrl, "Check")),
	}
	imp.Eventually = &OverlapGateImpEventually{
		Check: newOverlapGateMockCheckMethod(_imptest.NewDependencyMethod(ctrl, "Check").AsEventually()),
	}
	mock := &mockOverlapGateImpl{ctrl: ctrl}
	return mock, imp
}

type mockOverlapGateImpl struct {
	ctrl *_imptest.Imp
}

// Check implements reconcile.OverlapGate.Check.
func (impl *mockOverlapGateImpl) Check(ctx context.Context, learning reconcile.Learning, candidate store.Memory) (bool, string, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Check",
		Args:         []any{ctx, learning, candidate},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 bool
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(bool); ok {
			result1 = value
		}
	}

	var result2 string
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(string); ok {
			result2 = value
		}
	}

	var result3 error
	if len(resp.ReturnValues) > 2 {
		if value, ok := resp.ReturnValues[2].(error); ok {
			result3 = value
		}
	}

	return result1, result2, result3
}

// newOverlapGateMockCheckMethod creates a typed method wrapper.
func newOverlapGateMockCheckMethod(dm *_imptest.DependencyMethod) *OverlapGateMockCheckMethod {
	return &OverlapGateMockCheckMethod{DependencyMethod: dm}
}
