// Code generated by impgen. DO NOT EDIT.
// impgen:hash:9d57a0f43ec3a043

package reconcile_test

import (
	context "context"
	reconcile "engram/internal/reconcile"
	store "engram/internal/store"
	_imptest "github.com/toejough/imptest"
)

type StoreImp struct {
	FindSimilar *StoreMockFindSimilarMethod
	Create      *StoreMockCreateMethod
	Update      *StoreMockUpdateMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *StoreImpEventually
}

type StoreImpEventually struct {
	FindSimilar *StoreMockFindSimilarMethod
	Create      *StoreMockCreateMethod
	Update      *StoreMockUpdateMethod
}

type StoreMockCreateArgs struct {
	Ctx context.Context
	M   *store.Memory
}

type StoreMockCreateCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *StoreMockCreateCall) GetArgs() StoreMockCreateArgs {
	raw := c.RawArgs()
	return StoreMockCreateArgs{
		Ctx: raw[0].(context.Context),
		M:   raw[1].(*store.Memory),
	}
}

// Return specifies the typed values the mock should return.
func (c *StoreMockCreateCall) Return(result0 error) {
	c.DependencyCall.Return(result0)
}

type StoreMockCreateMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (meth *StoreMockCreateMethod) ArgsEqual(ctx context.Context, m *store.Memory) *StoreMockCreateCall {
	call := meth.DependencyMethod.ArgsEqual(ctx, m)
	return &StoreMockCreateCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *StoreMockCreateMethod) ArgsShould(matchers ...any) *StoreMockCreateCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &StoreMockCreateCall{DependencyCall: call}
}

type StoreMockFindSimilarArgs struct {
	Ctx   context.Context
	Query string
	K     int
}

type StoreMockFindSimilarCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *StoreMockFindSimilarCall) GetArgs() StoreMockFindSimilarArgs {
	raw := c.RawArgs()
	return StoreMockFindSimilarArgs{
		Ctx:   raw[0].(context.Context),
		Query: raw[1].(string),
		K:     raw[2].(int),
	}
}

// Return specifies the typed values the mock should return.
func (c *StoreMockFindSimilarCall) Return(result0 []store.ScoredMemory, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type StoreMockFindSimilarMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *StoreMockFindSimilarMethod) ArgsEqual(ctx context.Context, query string, k int) *StoreMockFindSimilarCall {
	call := m.DependencyMethod.ArgsEqual(ctx, query, k)
	return &StoreMockFindSimilarCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *StoreMockFindSimilarMethod) ArgsShould(matchers ...any) *StoreMockFindSimilarCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &StoreMockFindSimilarCall{DependencyCall: call}
}

type StoreMockUpdateArgs struct {
	Ctx context.Context
	M   *store.Memory
}

type StoreMockUpdateCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *StoreMockUpdateCall) GetArgs() StoreMockUpdateArgs {
	raw := c.RawArgs()
	return StoreMockUpdateArgs{
		Ctx: raw[0].(context.Context),
		M:   raw[1].(*store.Memory),
	}
}

// Return specifies the typed values the mock should return.
func (c *StoreMockUpdateCall) Return(result0 error) {
	c.DependencyCall.Return(result0)
}

type StoreMockUpdateMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (meth *StoreMockUpdateMethod) ArgsEqual(ctx context.Context, m *store.Memory) *StoreMockUpdateCall {
	call := meth.DependencyMethod.ArgsEqual(ctx, m)
	return &StoreMockUpdateCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *StoreMockUpdateMethod) ArgsShould(matchers ...any) *StoreMockUpdateCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &StoreMockUpdateCall{DependencyCall: call}
}

// MockStore creates a mock Store and returns (mock, expectation handle).
func MockStore(t _imptest.TestReporter) (reconcile.Store, *StoreImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &StoreImp{
		FindSimilar: newStoreMockFindSimilarMethod(_imptest.NewDependencyMethod(ctrl, "FindSimilar")),
		Create:      newStoreMockCreateMethod(_imptest.NewDependencyMethod(ctrl, "Create")),
		Update:      newStoreMockUpdateMethod(_imptest.NewDependencyMethod(ctrl, "Update")),
	}
	imp.Eventually = &StoreImpEventually{
		FindSimilar: newStoreMockFindSimilarMethod(_imptest.NewDependencyMethod(ctrl, "FindSimilar").AsEventually()),
		Create:      newStoreMockCreateMethod(_imptest.NewDependencyMethod(ctrl, "Create").AsEventually()),
		Update:      newStoreMockUpdateMethod(_imptest.NewDependencyMethod(ctrl, "Update").AsEventually()),
	}
	mock := &mockStoreImpl{ctrl: ctrl}
	return mock, imp
}

type mockStoreImpl struct {
	ctrl *_imptest.Imp
}

// Create implements reconcile.Store.Create.
func (impl *mockStoreImpl) Create(ctx context.Context, m *store.Memory) error {
	call := &_imptest.GenericCall{
		MethodName:   "Create",
		Args:         []any{ctx, m},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// FindSimilar implements reconcile.Store.FindSimilar.
func (impl *mockStoreImpl) FindSimilar(ctx context.Context, query string, k int) ([]store.ScoredMemory, error) {
	call := &_imptest.GenericCall{
		MethodName:   "FindSimilar",
		Args:         []any{ctx, query, k},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []store.ScoredMemory
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]store.ScoredMemory); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Update implements reconcile.Store.Update.
func (impl *mockStoreImpl) Update(ctx context.Context, m *store.Memory) error {
	call := &_imptest.GenericCall{
		MethodName:   "Update",
		Args:         []any{ctx, m},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// newStoreMockCreateMethod creates a typed method wrapper.
func newStoreMockCreateMethod(dm *_imptest.DependencyMethod) *StoreMockCreateMethod {
	return &StoreMockCreateMethod{DependencyMethod: dm}
}

// newStoreMockFindSimilarMethod creates a typed method wrapper.
func newStoreMockFindSimilarMethod(dm *_imptest.DependencyMethod) *StoreMockFindSimilarMethod {
	return &StoreMockFindSimilarMethod{DependencyMethod: dm}
}

// newStoreMockUpdateMethod creates a typed method wrapper.
func newStoreMockUpdateMethod(dm *_imptest.DependencyMethod) *StoreMockUpdateMethod {
	return &StoreMockUpdateMethod{DependencyMethod: dm}
}
