// Code generated by impgen. DO NOT EDIT.
// impgen:hash:21907da9861740ab

package catchup_test

import (
	context "context"
	catchup "engram/internal/catchup"
	_imptest "github.com/toejough/imptest"
)

type EvaluatorImp struct {
	FindMissed *EvaluatorMockFindMissedMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *EvaluatorImpEventually
}

type EvaluatorImpEventually struct {
	FindMissed *EvaluatorMockFindMissedMethod
}

type EvaluatorMockFindMissedArgs struct {
	Ctx        context.Context
	Transcript []byte
	Captured   []catchup.CapturedEvent
}

type EvaluatorMockFindMissedCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *EvaluatorMockFindMissedCall) GetArgs() EvaluatorMockFindMissedArgs {
	raw := c.RawArgs()
	return EvaluatorMockFindMissedArgs{
		Ctx:        raw[0].(context.Context),
		Transcript: raw[1].([]byte),
		Captured:   raw[2].([]catchup.CapturedEvent),
	}
}

// Return specifies the typed values the mock should return.
func (c *EvaluatorMockFindMissedCall) Return(result0 []catchup.MissedCorrection, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type EvaluatorMockFindMissedMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *EvaluatorMockFindMissedMethod) ArgsEqual(ctx context.Context, transcript []byte, captured []catchup.CapturedEvent) *EvaluatorMockFindMissedCall {
	call := m.DependencyMethod.ArgsEqual(ctx, transcript, captured)
	return &EvaluatorMockFindMissedCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *EvaluatorMockFindMissedMethod) ArgsShould(matchers ...any) *EvaluatorMockFindMissedCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &EvaluatorMockFindMissedCall{DependencyCall: call}
}

// MockEvaluator creates a mock Evaluator and returns (mock, expectation handle).
func MockEvaluator(t _imptest.TestReporter) (catchup.Evaluator, *EvaluatorImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &EvaluatorImp{
		FindMissed: newEvaluatorMockFindMissedMethod(_imptest.NewDependencyMethod(ctrl, "FindMissed")),
	}
	imp.Eventually = &EvaluatorImpEventually{
		FindMissed: newEvaluatorMockFindMissedMethod(_imptest.NewDependencyMethod(ctrl, "FindMissed").AsEventually()),
	}
	mock := &mockEvaluatorImpl{ctrl: ctrl}
	return mock, imp
}

type mockEvaluatorImpl struct {
	ctrl *_imptest.Imp
}

// FindMissed implements catchup.Evaluator.FindMissed.
func (impl *mockEvaluatorImpl) FindMissed(ctx context.Context, transcript []byte, captured []catchup.CapturedEvent) ([]catchup.MissedCorrection, error) {
	call := &_imptest.GenericCall{
		MethodName:   "FindMissed",
		Args:         []any{ctx, transcript, captured},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []catchup.MissedCorrection
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]catchup.MissedCorrection); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newEvaluatorMockFindMissedMethod creates a typed method wrapper.
func newEvaluatorMockFindMissedMethod(dm *_imptest.DependencyMethod) *EvaluatorMockFindMissedMethod {
	return &EvaluatorMockFindMissedMethod{DependencyMethod: dm}
}
