// Code generated by impgen. DO NOT EDIT.
// impgen:hash:797303ec5e47e88b

package surface_test

import (
	context "context"
	store "engram/internal/store"
	surface "engram/internal/surface"
	_imptest "github.com/toejough/imptest"
)

type StoreImp struct {
	Surface            *StoreMockSurfaceMethod
	IncrementSurfacing *StoreMockIncrementSurfacingMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *StoreImpEventually
}

type StoreImpEventually struct {
	Surface            *StoreMockSurfaceMethod
	IncrementSurfacing *StoreMockIncrementSurfacingMethod
}

type StoreMockIncrementSurfacingArgs struct {
	Ctx context.Context
	Ids []string
}

type StoreMockIncrementSurfacingCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *StoreMockIncrementSurfacingCall) GetArgs() StoreMockIncrementSurfacingArgs {
	raw := c.RawArgs()
	return StoreMockIncrementSurfacingArgs{
		Ctx: raw[0].(context.Context),
		Ids: raw[1].([]string),
	}
}

// Return specifies the typed values the mock should return.
func (c *StoreMockIncrementSurfacingCall) Return(result0 error) {
	c.DependencyCall.Return(result0)
}

type StoreMockIncrementSurfacingMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *StoreMockIncrementSurfacingMethod) ArgsEqual(ctx context.Context, ids []string) *StoreMockIncrementSurfacingCall {
	call := m.DependencyMethod.ArgsEqual(ctx, ids)
	return &StoreMockIncrementSurfacingCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *StoreMockIncrementSurfacingMethod) ArgsShould(matchers ...any) *StoreMockIncrementSurfacingCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &StoreMockIncrementSurfacingCall{DependencyCall: call}
}

type StoreMockSurfaceArgs struct {
	Ctx   context.Context
	Query string
	K     int
}

type StoreMockSurfaceCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *StoreMockSurfaceCall) GetArgs() StoreMockSurfaceArgs {
	raw := c.RawArgs()
	return StoreMockSurfaceArgs{
		Ctx:   raw[0].(context.Context),
		Query: raw[1].(string),
		K:     raw[2].(int),
	}
}

// Return specifies the typed values the mock should return.
func (c *StoreMockSurfaceCall) Return(result0 []store.ScoredMemory, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

type StoreMockSurfaceMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *StoreMockSurfaceMethod) ArgsEqual(ctx context.Context, query string, k int) *StoreMockSurfaceCall {
	call := m.DependencyMethod.ArgsEqual(ctx, query, k)
	return &StoreMockSurfaceCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *StoreMockSurfaceMethod) ArgsShould(matchers ...any) *StoreMockSurfaceCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &StoreMockSurfaceCall{DependencyCall: call}
}

// MockStore creates a mock Store and returns (mock, expectation handle).
func MockStore(t _imptest.TestReporter) (surface.Store, *StoreImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &StoreImp{
		Surface:            newStoreMockSurfaceMethod(_imptest.NewDependencyMethod(ctrl, "Surface")),
		IncrementSurfacing: newStoreMockIncrementSurfacingMethod(_imptest.NewDependencyMethod(ctrl, "IncrementSurfacing")),
	}
	imp.Eventually = &StoreImpEventually{
		Surface:            newStoreMockSurfaceMethod(_imptest.NewDependencyMethod(ctrl, "Surface").AsEventually()),
		IncrementSurfacing: newStoreMockIncrementSurfacingMethod(_imptest.NewDependencyMethod(ctrl, "IncrementSurfacing").AsEventually()),
	}
	mock := &mockStoreImpl{ctrl: ctrl}
	return mock, imp
}

type mockStoreImpl struct {
	ctrl *_imptest.Imp
}

// IncrementSurfacing implements surface.Store.IncrementSurfacing.
func (impl *mockStoreImpl) IncrementSurfacing(ctx context.Context, ids []string) error {
	call := &_imptest.GenericCall{
		MethodName:   "IncrementSurfacing",
		Args:         []any{ctx, ids},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// Surface implements surface.Store.Surface.
func (impl *mockStoreImpl) Surface(ctx context.Context, query string, k int) ([]store.ScoredMemory, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Surface",
		Args:         []any{ctx, query, k},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []store.ScoredMemory
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]store.ScoredMemory); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newStoreMockIncrementSurfacingMethod creates a typed method wrapper.
func newStoreMockIncrementSurfacingMethod(dm *_imptest.DependencyMethod) *StoreMockIncrementSurfacingMethod {
	return &StoreMockIncrementSurfacingMethod{DependencyMethod: dm}
}

// newStoreMockSurfaceMethod creates a typed method wrapper.
func newStoreMockSurfaceMethod(dm *_imptest.DependencyMethod) *StoreMockSurfaceMethod {
	return &StoreMockSurfaceMethod{DependencyMethod: dm}
}
