// Code generated by impgen. DO NOT EDIT.
// impgen:hash:3c5c8172d823b42f

package surface_test

import (
	store "engram/internal/store"
	surface "engram/internal/surface"
	_imptest "github.com/toejough/imptest"
)

type FormatterImp struct {
	FormatSurfacing *FormatterMockFormatSurfacingMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *FormatterImpEventually
}

type FormatterImpEventually struct {
	FormatSurfacing *FormatterMockFormatSurfacingMethod
}

type FormatterMockFormatSurfacingArgs struct {
	Memories []store.ScoredMemory
	HookType string
}

type FormatterMockFormatSurfacingCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *FormatterMockFormatSurfacingCall) GetArgs() FormatterMockFormatSurfacingArgs {
	raw := c.RawArgs()
	return FormatterMockFormatSurfacingArgs{
		Memories: raw[0].([]store.ScoredMemory),
		HookType: raw[1].(string),
	}
}

// Return specifies the typed values the mock should return.
func (c *FormatterMockFormatSurfacingCall) Return(result0 string) {
	c.DependencyCall.Return(result0)
}

type FormatterMockFormatSurfacingMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *FormatterMockFormatSurfacingMethod) ArgsEqual(memories []store.ScoredMemory, hookType string) *FormatterMockFormatSurfacingCall {
	call := m.DependencyMethod.ArgsEqual(memories, hookType)
	return &FormatterMockFormatSurfacingCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *FormatterMockFormatSurfacingMethod) ArgsShould(matchers ...any) *FormatterMockFormatSurfacingCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &FormatterMockFormatSurfacingCall{DependencyCall: call}
}

// MockFormatter creates a mock Formatter and returns (mock, expectation handle).
func MockFormatter(t _imptest.TestReporter) (surface.Formatter, *FormatterImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &FormatterImp{
		FormatSurfacing: newFormatterMockFormatSurfacingMethod(_imptest.NewDependencyMethod(ctrl, "FormatSurfacing")),
	}
	imp.Eventually = &FormatterImpEventually{
		FormatSurfacing: newFormatterMockFormatSurfacingMethod(_imptest.NewDependencyMethod(ctrl, "FormatSurfacing").AsEventually()),
	}
	mock := &mockFormatterImpl{ctrl: ctrl}
	return mock, imp
}

type mockFormatterImpl struct {
	ctrl *_imptest.Imp
}

// FormatSurfacing implements surface.Formatter.FormatSurfacing.
func (impl *mockFormatterImpl) FormatSurfacing(memories []store.ScoredMemory, hookType string) string {
	call := &_imptest.GenericCall{
		MethodName:   "FormatSurfacing",
		Args:         []any{memories, hookType},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}

// newFormatterMockFormatSurfacingMethod creates a typed method wrapper.
func newFormatterMockFormatSurfacingMethod(dm *_imptest.DependencyMethod) *FormatterMockFormatSurfacingMethod {
	return &FormatterMockFormatSurfacingMethod{DependencyMethod: dm}
}
