// Code generated by impgen. DO NOT EDIT.
// impgen:hash:2af94128342e2d3f

package surface_test

import (
	audit "engram/internal/audit"
	surface "engram/internal/surface"
	_imptest "github.com/toejough/imptest"
)

type AuditLogImp struct {
	Log *AuditLogMockLogMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *AuditLogImpEventually
}

type AuditLogImpEventually struct {
	Log *AuditLogMockLogMethod
}

type AuditLogMockLogArgs struct {
	Entry audit.Entry
}

type AuditLogMockLogCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *AuditLogMockLogCall) GetArgs() AuditLogMockLogArgs {
	raw := c.RawArgs()
	return AuditLogMockLogArgs{
		Entry: raw[0].(audit.Entry),
	}
}

// Return specifies the typed values the mock should return.
func (c *AuditLogMockLogCall) Return(result0 error) {
	c.DependencyCall.Return(result0)
}

type AuditLogMockLogMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *AuditLogMockLogMethod) ArgsEqual(entry audit.Entry) *AuditLogMockLogCall {
	call := m.DependencyMethod.ArgsEqual(entry)
	return &AuditLogMockLogCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *AuditLogMockLogMethod) ArgsShould(matchers ...any) *AuditLogMockLogCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &AuditLogMockLogCall{DependencyCall: call}
}

// MockAuditLog creates a mock AuditLog and returns (mock, expectation handle).
func MockAuditLog(t _imptest.TestReporter) (surface.AuditLog, *AuditLogImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &AuditLogImp{
		Log: newAuditLogMockLogMethod(_imptest.NewDependencyMethod(ctrl, "Log")),
	}
	imp.Eventually = &AuditLogImpEventually{
		Log: newAuditLogMockLogMethod(_imptest.NewDependencyMethod(ctrl, "Log").AsEventually()),
	}
	mock := &mockAuditLogImpl{ctrl: ctrl}
	return mock, imp
}

type mockAuditLogImpl struct {
	ctrl *_imptest.Imp
}

// Log implements surface.AuditLog.Log.
func (impl *mockAuditLogImpl) Log(entry audit.Entry) error {
	call := &_imptest.GenericCall{
		MethodName:   "Log",
		Args:         []any{entry},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// newAuditLogMockLogMethod creates a typed method wrapper.
func newAuditLogMockLogMethod(dm *_imptest.DependencyMethod) *AuditLogMockLogMethod {
	return &AuditLogMockLogMethod{DependencyMethod: dm}
}
